import '../styles/main.css';
import '../styles/components/head.css';
import '../styles/components/hero.css';
import '../styles/components/description.css';
import '../styles/components/procedures.css';
import '../styles/components/price.css';
import '../styles/components/reviews.css';
import '../styles/components/form.css';
import '../styles/components/foot.css';